version: '3'

services:
  server:
    build:
      context: ./server
    command: ["-port", "${PORT}", "-debug"]

  publisher:
    build:
      context: ./publisher
    depends_on:
      - server
    command: ["-addr", "server:${PORT}", "-debug"]

  subscriber:
    build:
      context: ./subscriber
    depends_on:
      - server
    command: ["-addr", "server:${PORT}", "-debug"]
