version: '2.4'

services:
  webserver:
    container_name: teso_task
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - PORT=3342
      - DEBUG=TRUE
    ports:
      - "3342:3342"
